/**
 * pages.js — 待测页面定义
 * 每个页面包含: name, url, requiresAuth, waitFor, masks
 */
'use strict';

/** @type {Array<{ name: string, url: string, requiresAuth: boolean, waitFor: string, masks: string[] }>} */
const pages = [
  {
    name: 'index',
    url: '/index.html',
    requiresAuth: false,
    waitFor: 'body',
    masks: [],
  },
  {
    name: 'login',
    url: '/?tmpui_page=/login',
    requiresAuth: false,
    waitFor: 'body',
    masks: [],
  },
  {
    name: 'register',
    url: '/?tmpui_page=/reg',
    requiresAuth: false,
    waitFor: 'body',
    masks: [],
  },
  {
    name: 'filelist-list',
    url: '/?tmpui_page=/vx&module=filelist&view=list',
    requiresAuth: true,
    waitFor: '#vx-fl-list',
    masks: [
      '#vx-fl-list-body',
      '#vx-fl-folder-count',
      '#vx-fl-file-count',
      '#vx-fl-total-size',
      '#vx-fl-cache-saved-at',
      '#vx-fl-sidebar-title',
    ],
  },
  {
    name: 'direct-dashboard',
    url: '/?tmpui_page=/vx&module=direct&tab=dashboard',
    requiresAuth: true,
    waitFor: '#vx-direct-panel-dashboard',
    masks: [
      '#vx-direct-count',
      '#vx-direct-folder-count',
      '#vx-direct-quota',
      '#vx-direct-total-transfer',
      '#vx-direct-total-downloads',
      '#vx-direct-usage-card',
      '#vx-direct-brand-logo-preview',
      '#vx-direct-domain-text',
      '#vx-direct-brand-status',
    ],
  },
  {
    name: 'direct-files',
    url: '/?tmpui_page=/vx&module=direct&tab=files&sort_by=0&sort_type=0',
    requiresAuth: true,
    waitFor: '#vx-direct-panel-files',
    masks: ['#vx-direct-files-list-body'],
  },
  {
    name: 'direct-folders',
    url: '/?tmpui_page=/vx&module=direct&tab=folders&sort_by=0&sort_type=0',
    requiresAuth: true,
    waitFor: '#vx-direct-panel-folders',
    masks: ['#vx-direct-folders-list-body'],
  },
  {
    name: 'direct-domain',
    url: '/?tmpui_page=/vx&module=direct&tab=domain',
    requiresAuth: true,
    waitFor: '#vx-direct-panel-domain',
    masks: ['#vx-direct-domain-status'],
  },
  {
    name: 'direct-api',
    url: '/?tmpui_page=/vx&module=direct&tab=api',
    requiresAuth: true,
    waitFor: '#vx-direct-panel-api',
    masks: [],
  },
  {
    name: 'notes',
    url: '/?tmpui_page=/vx&module=notes',
    requiresAuth: true,
    waitFor: '#vx-notes-layout',
    masks: [
      '#vx-notes-list',
      '#vx-notes-count-footer',
      '#vx-notes-editor',
    ],
  },
  {
    name: 'ai',
    url: '/?tmpui_page=/vx&module=ai',
    requiresAuth: true,
    waitFor: '#vx-ai-messages',
    masks: [
      '#vx-ai-messages',
      '#vx-ai-quota-text',
      '#vx-ai-quota-progress',
      '#vx-ai-status',
    ],
  },
  {
    name: 'shop',
    url: '/?tmpui_page=/vx&module=shop',
    requiresAuth: true,
    waitFor: '.vx-shop-card',
    masks: ['#vx-shop-special'],
  },
  {
    name: 'shop-purchased',
    url: '/?tmpui_page=/vx&module=shop&tab=purchased',
    requiresAuth: true,
    waitFor: '#vx-shop-purchased',
    masks: ['#vx-orders-list'],
  },
  {
    name: 'points',
    url: '/?tmpui_page=/vx&module=points',
    requiresAuth: true,
    waitFor: '#vx-points-summary',
    masks: ['#vx-points-balance', '#vx-point-log-list'],
  },
  {
    name: 'points-selling',
    url: '/?tmpui_page=/vx&module=points&tab=selling',
    requiresAuth: true,
    waitFor: '#vx-points-selling',
    masks: ['#vx-points-selling-body'],
  },
  {
    name: 'points-mall',
    url: '/?tmpui_page=/vx&module=points&tab=mall',
    requiresAuth: true,
    waitFor: '#vx-points-mall',
    masks: ['#vx-mall-products'],
  },
  {
    name: 'points-orders',
    url: '/?tmpui_page=/vx&module=points&tab=orders',
    requiresAuth: true,
    waitFor: '#vx-points-orders',
    masks: ['#vx-mall-orders'],
  },
  {
    name: 'settings',
    url: '/?tmpui_page=/vx&module=settings',
    requiresAuth: true,
    waitFor: '#vx-account-settings',
    masks: [
      '#vx-google-status',
      '#vx-send-code-btn',
      '#vx-profile-avatar',
      '#vx-profile-name',
      '#vx-profile-intro',
      '#vx-profile-uid',
      '#vx-profile-rank',
      '#vx-stat-acv',
      '#vx-stat-storage',
      '#vx-stat-shares',
    ],
  },
  {
    name: '404',
    url: '/?tmpui_page=/404',
    requiresAuth: false,
    waitFor: 'body',
    masks: [],
  },
  {
    name: '403',
    url: '/?tmpui_page=/403',
    requiresAuth: false,
    waitFor: 'body',
    masks: [],
  },
  {
    name: '504',
    url: '/?tmpui_page=/504',
    requiresAuth: false,
    waitFor: 'body',
    masks: [],
  },
  {
    name: 'tos',
    url: '/?tmpui_page=/tos.html',
    requiresAuth: false,
    waitFor: 'body',
    masks: [],
  },
  {
    name: 'privacy',
    url: '/?tmpui_page=/privacy.html',
    requiresAuth: false,
    waitFor: 'body',
    masks: [],
  },
];

module.exports = { pages };
